version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "card-grading-backend"
s3_prefix = "card-grading-backend"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = []
